import numpy as np
arr = np.array([[[3,4,5,6],[2,5,7,8]],[[1,4,6,7], [1,2,3,4]]])
print(arr)
print()
print(arr.sum(axis=0))
print()
print(arr.sum(axis=1))
print()
print(arr.sum(axis=2).sum(axis=1).sum(axis=0))
print()